# commands for recreating letter2004.pdf

# create 1 pdf files from the latex file letter2004.tex.

all: letter2004.pdf

sources: letter2004.tex

letter2004.pdf: sources
	pdflatex letter2004

clean:
	/bin/rm -f *~ *.out *.log *.aux

